name: Build Artifcats

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code âœ…
        uses: actions/checkout@v3.5.3

      - name: Install dependencies ğŸ”§
        run: npm install
      
      - name: Build ğŸ—ï¸
        run: npm run build

      - name: Git Push Action For Coding Page
        uses: AnonyStar/git-push@v2
        env:
          GITHUB_EMAIL: "action@github.com"
          GITHUB_USERNAME: "Github Action"
          PUBLISH_BRANCH: build
          PUBLISH_DIR: ./build
