name: Build Artifcats

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code âœ…
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1

      - name: Install dependencies ğŸ”§
        run: npm install
      
      - name: Build ğŸ—ï¸
        run: npm run build

      - name: Checking build
        run: ls

      - name: Push dir to Git
        uses: liziwl/git-push-action@v1.0.4
        with:
          git_token: ${{ secrets.GIT_TOKEN }}
          push_dir: ./dist
          commit_user: action@github.com
          commit_email: Github Actions
          branch: build
